import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './Providers';
import Navbar from './components/navbar';
import Footer from './components/footer';
import { AuthProvider } from './context/AuthContext';

export const metadata: Metadata = {
	title: 'My Anime List V2',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			style={{
				scrollBehavior: 'smooth',
				scrollPadding: '350px',
			}}
		>
			<body className='bg-firsto '>
				<Providers>
					<AuthProvider>
						<Navbar></Navbar>
						{children}
						<Footer></Footer>
					</AuthProvider>
				</Providers>
			</body>
		</html>
	);
}
